In [1]:
import pandas as pd

Graphics ideas

Visualization

1
Europe - NUTS 2 (= regions, CCAA)
subject: share of early leavers in 2019 compared to 2020 charta goal
Beispiel
https://ec.europa.eu/eurostat/documents/4187653/10321620/EU-INSTA-MAP-EDUCATI0N-EARLY+LEAVERS.jpg/f71a5ddd-5243-fb44-dd4c-a84475b7e291?t=1601909979664
> colour map Europe with "big 10%" charta or colour range <= 10 for countries who have achieved the goal

2
Spain
subject: early leavers evolution Spain
x: time, 2010 - 2019 
y: % early leavers
line: a) male/ b) female
> line orange f, turquoise m

3
Europe
macroeconomic cost of early leavers
comparison (3 times Denmark´s national budget > 3 x Denmark map)


4
Europe
subject: correlation education spending/ share of early leavers 2019
x: spending % GDP on education
y: % of early leavers 2019
scatter points: countries
> scatter plot
> clusters

5
Spain
subject: correlation share early leavers/ share families in danger of social exclusiom
- early leavers by CCAA
- families in danger of social exclusion by CCAA
a) dashboard with 2 heat maps or b) 1 interactive map with successive "mapping" of both phenomenas

6
countries OECD Pisa
subject: difference in PISA results between native students and students 1. generation immigration
> dashboard
a) horizontal bar graph: score native vs score immigrant by country, ascendant
b) horizontal bar graph: difference between both scores per country, asscendant

comparison bar within a bar/ stacked bar

7
Barcelona
subject: % of pupils with free meals per neighborhood/ % of pupils that repeat class
a) city heatmap - preferible
b) scatter plot 
x: free meals
y: repeat class
dots: neighborhoods

easiest: map
impressive: scatter plot > linear correlation

8
Barcelona
subject: deficiency in catalan and maths at the 6a primaria (12 yrs) and 4a ESO (15 yrs)
dashboard with 2 horizontal bar charts (cat + math) by neighboorhood and % od pupils that do not pass the basic knowledge test
Dataset: bcn_informe_2019, 17.1 and 17.3.

9
Barcelona
"ghettoisation" of immigrant
flow chart with 2 examples



10
prediction model: time series forecasting 
a) Europe (tot, m, f) or
b) Spain (CCAA)


box-whisker-plot for Spain/ Barcelona
bump charts

In [12]:
# graph 1 NUTS early leavers

df_vis1_NUTS_earl_leav = pd.read_excel(r'C:\Users\dgruh\ironhack\assignments\week9\proyecto final\datasets\Graphics\Graphic1_early_leav_NUTS2.xls')
df_vis1_NUTS_earl_leav.head()

                                       Region NUTS 2 % early leavers
0          European Union - 28 countries (2013-2020)            10.3
1  Région de Bruxelles-Capitale/Brussels Hoofdste...            11.8
2  Région de Bruxelles-Capitale/Brussels Hoofdste...            11.8
3                                      Vlaams Gewest             6.2
4                                    Prov. Antwerpen             7.3

In [13]:
df_vis1_NUTS_earl_leav.drop_duplicates(subset = 'Region NUTS 2', inplace = True)
df_vis1_NUTS_earl_leav

                                         Region NUTS 2 % early leavers
0            European Union - 28 countries (2013-2020)            10.3
1    Région de Bruxelles-Capitale/Brussels Hoofdste...            11.8
3                                        Vlaams Gewest             6.2
4                                      Prov. Antwerpen             7.3
5                                   Prov. Limburg (BE)             6.3
..                                                 ...             ...
430                          Van, Mus, Bitlis, Hakkari            47.9
431                                  Güneydogu Anadolu            47.8
432                         Gaziantep, Adiyaman, Kilis            41.6
433                              Sanliurfa, Diyarbakir            52.6
434                      Mardin, Batman, Sirnak, Siirt              46

[410 rows x 2 columns]

In [17]:
df_vis1_NUTS_earl_leav.to_excel(r'C:\Users\dgruh\ironhack\assignments\week9\proyecto final\datasets\Graphics\Graphic1_early_leav_NUTS2.xls')

In [ ]:
# graph 2